# Generated by Django 5.1.4 on 2026-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_hotel_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPaymentMethod',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"CustomPaymentMethod"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('spent_at', models.DateTimeField(db_column='spentAt')),
                ('category', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=20)),
                ('custom_method_label', models.CharField(blank=True, db_column='customMethodLabel', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"Expense"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=100)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"Hotel"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthClosing',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('closed_at', models.DateTimeField(db_column='closedAt')),
                ('totals_json', models.JSONField(blank=True, db_column='totalsJson', null=True)),
            ],
            options={
                'db_table': '"MonthClosing"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('paid_at', models.DateTimeField(db_column='paidAt')),
                ('method', models.CharField(max_length=20)),
                ('custom_method_label', models.CharField(blank=True, db_column='customMethodLabel', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"Payment"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='fullName', max_length=255)),
                ('created_at', models.DateTimeField(db_column='createdAt', null=True)),
            ],
            options={
                'db_table': '"Profile"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('room_type', models.CharField(db_column='roomType', max_length=20)),
                ('capacity', models.IntegerField()),
                ('base_price', models.DecimalField(db_column='basePrice', decimal_places=2, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"Room"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(db_column='guestName', max_length=255)),
                ('guest_phone', models.CharField(blank=True, db_column='guestPhone', max_length=50, null=True)),
                ('check_in_date', models.DateTimeField(db_column='checkInDate')),
                ('check_out_date', models.DateTimeField(db_column='checkOutDate')),
                ('status', models.CharField(max_length=20)),
                ('price_per_night', models.DecimalField(db_column='pricePerNight', decimal_places=2, max_digits=20)),
                ('weekly_discount_amount', models.DecimalField(db_column='weeklyDiscountAmount', decimal_places=2, default=0, max_digits=20)),
                ('manual_adjustment_amount', models.DecimalField(db_column='manualAdjustmentAmount', decimal_places=2, default=0, max_digits=20)),
                ('deposit_expected', models.DecimalField(db_column='depositExpected', decimal_places=2, default=0, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"Stay"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('transferred_at', models.DateTimeField(db_column='transferredAt')),
                ('from_method', models.CharField(db_column='fromMethod', max_length=100)),
                ('to_method', models.CharField(db_column='toMethod', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"Transfer"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.TextField(db_column='passwordHash')),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"User"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"UserRole"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('withdrawn_at', models.DateTimeField(db_column='withdrawnAt')),
                ('method', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': '"Withdrawal"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('hotel_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_guest',
                'ordering': ['name'],
            },
        ),
    ]
