# Generated by Django 5.1.4 on 2026-07-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_custompaymentmethod_expense_hotel_monthclosing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompaymentmethod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='monthclosing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stay',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={},
        ),
    ]
