# Generated by Django 5.1.4 on 2026-07-04 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_create_core_tables_if_missing'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='custompaymentmethod',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='expense',
                    name='created_by',
                    field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.user'),
                ),
                migrations.AddField(
                    model_name='expense',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='monthclosing',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='payment',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='payment',
                    name='stay',
                    field=models.ForeignKey(db_column='stayId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.stay'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='profile',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.PROTECT, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='room',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='stay',
                    name='guest_id',
                    field=models.CharField(blank=True, db_column='guestId', max_length=36, null=True),
                ),
                migrations.AddField(
                    model_name='stay',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='stay',
                    name='room',
                    field=models.ForeignKey(db_column='roomId', default=None, on_delete=django.db.models.deletion.PROTECT, to='api.room'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='transfer',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='userrole',
                    name='user',
                    field=models.ForeignKey(db_column='userId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='withdrawal',
                    name='created_by',
                    field=models.ForeignKey(blank=True, db_column='createdById', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='api.user'),
                ),
                migrations.AddField(
                    model_name='withdrawal',
                    name='hotel',
                    field=models.ForeignKey(db_column='hotelId', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
                    preserve_default=False,
                ),
                migrations.AlterUniqueTogether(
                    name='custompaymentmethod',
                    unique_together={('hotel', 'name')},
                ),
                migrations.AlterUniqueTogether(
                    name='monthclosing',
                    unique_together={('hotel', 'month')},
                ),
                migrations.AlterModelTable(
                    name='custompaymentmethod',
                    table='CustomPaymentMethod',
                ),
                migrations.AlterModelTable(
                    name='expense',
                    table='Expense',
                ),
                migrations.AlterModelTable(
                    name='hotel',
                    table='Hotel',
                ),
                migrations.AlterModelTable(
                    name='monthclosing',
                    table='MonthClosing',
                ),
                migrations.AlterModelTable(
                    name='payment',
                    table='Payment',
                ),
                migrations.AlterModelTable(
                    name='profile',
                    table='Profile',
                ),
                migrations.AlterModelTable(
                    name='room',
                    table='Room',
                ),
                migrations.AlterModelTable(
                    name='stay',
                    table='Stay',
                ),
                migrations.AlterModelTable(
                    name='transfer',
                    table='Transfer',
                ),
                migrations.AlterModelTable(
                    name='user',
                    table='User',
                ),
                migrations.AlterModelTable(
                    name='userrole',
                    table='UserRole',
                ),
                migrations.AlterModelTable(
                    name='withdrawal',
                    table='Withdrawal',
                ),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(db_column='tokenVersion', default=0),
        ),
    ]
